# Generated by Django 4.1.7 on 2023-03-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='customeremail',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customername',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
    ]
